app/main/routes.py
# installed imports
import traceback
from flask_login import login_required, current_user
from flask import Blueprint, render_template, abort, flash, redirect, url_for

# local imports
from ..models import Case, User
from .. import logger, csrf

main = Blueprint("main", __name__)

# Index ---------------------------
@main.get("/")
@main.get("/case")
@login_required
def index():
    return render_template("main/index.html", cases=current_user.cases)


# User Account -------------------------------
@main.get("/profile")
@login_required
def account():
    return render_template("main/profile.html", title="Profile")


# Terms of Service -------------------------------
@main.get("/terms-of-service")
def terms_of_service():
    return render_template("main/tos.html", title="Terms of Service")


# About ---------------------------------
@main.get("/about")
def about():
    return render_template("main/about.html", title="About")


# Privacy Policy ---------------------------------
@main.get("/privacy-policy")
def privacy_policy():
    return render_template("main/privacy.html", title="Pricacy Policy")


# Case View ------------------------------------
@main.get("/case/<uid>")
@login_required
def show_case(uid):
    return render_template(
        "main/case.html",
        case=Case.query.filter_by(user_id=current_user.id, uid=uid).one_or_404(),
    )


# Delete Case -------------------------------
@main.get("/case/delete/<uid>")
@login_required
def delete_case(uid):
    try:
        from ..modules.secure_image_handler import SecureImageHandler

        handler = SecureImageHandler()
        get_case = Case.query.filter_by(user_id=current_user.id, uid=uid).one_or_404()
        for image in get_case.patient_images:
            handler.delete_image(image.id, current_user.id)
        get_case.delete()
        flash(f"Delete successful", "success")
        return redirect(url_for("main.index"))
    except:
        logger.error(traceback.format_exc())
        abort(500)

app/templates/email_layout.html
<body>
  <!-- ======= Header ======= -->
  <header
    id="header"
    style="
      transition: all 0.5s;
      z-index: 997;
      padding: 2rem;
      border-bottom: 1px solid #e6f2fb;
    "
  >
    <div
      style="
        --bs-gutter-x: 1.5rem;
        --bs-gutter-y: 0;
        width: 100%;
        padding-right: calc(var(--bs-gutter-x) * 0.5);
        padding-left: calc(var(--bs-gutter-x) * 0.5);
        margin-right: auto;
        margin-left: auto;
        align-items: center;
        justify-content: space-between;
        display: flex;

        @media (min-width: 576px) {
          .container {
            max-width: 540px;
          }
        }
        @media (min-width: 768px) {
          .container {
            max-width: 720px;
          }
        }
        @media (min-width: 992px) {
          .container {
            max-width: 960px;
          }
        }
        @media (min-width: 1200px) {
          .container {
            max-width: 1140px;
          }
        }
        @media (min-width: 1400px) {
          .container {
            max-width: 1320px;
          }
        }
      "
    >
      <h1
        class="logo"
        style="
          font-size: 28px;
          margin: 0;
          padding: 0;
          line-height: 1;
          font-weight: 300;
          letter-spacing: 0.5px;
          font-family: 'Poppins', sans-serif;
        "
      >
        <a
          style="color: #16507b"
          href="{{ url_for('main.index', _external=True, _scheme='https') }}"
        >
          <img
            src="{{ url_for('static', filename='img/phenofull.png', _external=True, _scheme='https') }}"
            alt="PhenoMap"
            style="max-height: 40px"
          />
        </a>
      </h1>
    </div>
  </header>
  <!-- End Header -->

  <div
    style="
      --bs-gutter-x: 1.5rem;
      --bs-gutter-y: 0;
      display: flex;
      flex-wrap: wrap;
      margin-top: calc(-1 * var(--bs-gutter-y));
      margin-right: 2rem;
      margin-left: 2rem;
    "
    class="row"
  >
    {% block email_content %} {% endblock %}
  </div>
</body>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />

    {% if title %}
    <title>PhenoMap - {{ title }}</title>
    {% else %}
    <title>PhenoMap - Genetic Disorder Classifier</title>
    {% endif %}

    <!-- Style -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap4.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/microns.css') }}"
    />
    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{{url_for('static', filename='img/favicon.png') }}"
    />
  </head>
  <body>
    <div class="container-scroller">
      <!-- Navbar -->
      <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a href="{{ url_for('main.index') }}" class="navbar-brand">
          <img
            src="{{ url_for('static', filename='img/pheno.png') }}"
            class="d-inline-block align-top"
            width="30"
            height="30"
            alt="PhenoMap"
          />
          PhenoMap
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="collapse justify-content-between navbar-collapse"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a href="{{ url_for('main.index') }}" class="nav-link">Cases</a>
            </li>
            <li class="nav-item">
              <a
                href="{{ url_for('main.index') }}"
                class="nav-link"
                onclick="addCase(JSON.parse('{{ current_user.email_verified | tojson}}'))"
                >New Case</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a href="{{ url_for('main.about') }}" class="nav-link">About</a>
            </li>
          </ul>
          {% if current_user.is_authenticated %}
          <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                {{ current_user.display_name() }}
              </a>
              <div
                class="dropdown-menu dropdown-menu-right"
                aria-labelledby="navbarDropdownMenuLink"
              >
                <a class="dropdown-item" href="{{ url_for('main.account') }}">
                  <i class="mu mu-cog text-primary"></i>
                  Edit Profile
                </a>
                {% if not current_user.email_verified %}
                <a id="resend-email" class="dropdown-item" href="#">
                  <i class="mu mu-refresh text-primary"></i>
                  Resend verification email
                </a>
                {% endif %}
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                  <i class="mu mu-external text-primary"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
          {% endif %}
        </div>
      </nav>

      <div class="container-fluid page-body-wrapper" style="margin-top: 5rem">
        <div class="main-panel">
          <!-- Main Content -->
          <div class="content-wrapper" style="min-height: 75vh">
            <div
              id="flash-container"
              class="position-fixed"
              style="z-index: 100; right: 1rem"
            >
              {% block alert_content %} {% with messages =
              get_flashed_messages(with_categories=true) %} {% if messages %} {%
              for category, message in messages %}
              <div
                class="toast align-items-center text-white {% if category == 'message' %} bg-info {% else %} bg-{{ category }} {% endif %} border-0"
                role="alert"
                aria-live="assertive"
                aria-atomic="true"
              >
                <div class="d-flex">
                  <div class="toast-body">{{ message }}</div>
                  <button
                    type="button"
                    class="mx-2 close"
                    data-dismiss="toast"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              </div>
              {% endfor %} {% endif %} {% endwith %} {% endblock %}
            </div>
            {% block content %} {% endblock %}
          </div>
          <!-- Footer -->
          <footer class="footer">
            <div class="card">
              <div class="card-body">
                <div
                  class="d-sm-flex justify-content-center justify-content-sm-between"
                >
                  <span
                    class="text-muted text-center text-sm-left d-block d-sm-inline-block"
                    >Copyright © 2025
                    <a
                      href="https://braintext.io/"
                      class="text-muted"
                      target="_blank"
                      >BrainText</a
                    >. All rights reserved.</span
                  >
                  <span
                    class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center text-muted"
                    >Made with ❤️ by
                    <a
                      href="https://github.com/kaosi-anikwe/phenomap"
                      class="text-muted"
                      target="_blank"
                      >Kaosi Anikwe.
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap4.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
  </body>
</html>